// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Minhaapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206184814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhaApi.Models.LoteMinerio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_lote");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_producao");

                    b.Property<string>("LocalizacaoAtual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localizacao_atual");

                    b.Property<string>("MinaOrigem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mina_origem");

                    b.Property<double?>("P")
                        .HasColumnType("double precision")
                        .HasColumnName("p");

                    b.Property<double?>("SiO2")
                        .HasColumnType("double precision")
                        .HasColumnName("si_o2");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<double>("TeorFe")
                        .HasColumnType("double precision")
                        .HasColumnName("teor_fe");

                    b.Property<double>("Toneladas")
                        .HasColumnType("double precision")
                        .HasColumnName("toneladas");

                    b.Property<double>("Umidade")
                        .HasColumnType("double precision")
                        .HasColumnName("umidade");

                    b.HasKey("Id");

                    b.ToTable("lotes_minerio");
                });
#pragma warning restore 612, 618
        }
    }
}
